### ISSUE TITLE
extension settings not accessible

### ISSUE THREAD

**Issue by JarmoCluyse** [Geeknerd1337/HyperBold#3]
extension settings are not accessible
![image](https://github.com/user-attachments/assets/8cd61752-3877-41ed-8718-c6f974687d37)

adding ```width: fit-content;``` to the body in popup.css would fix this issue

**Comment by Geeknerd1337** [comment]
Fixed, thank you for doing this.

**Comment by JarmoCluyse** [comment]
no problem,
thank you for writing the extension 
did you update the version in the chrome webstore?
I still get the old css in the extension
